### ISSUE TITLE
Always need root status

### ISSUE THREAD

**Issue by legraina** [singularityhub/singularity-compose#24]
Hi, I was wondering if it's normal that the root privileges are needed for most commands.
If it's the case, I think you should update the documentation to make it clear.
Thanks

**Comment by vsoch** [comment]
The constraint is what Singularity is able to do - I can’t do magic and remove the root requirement from where it’s needed. Anything with a port requires root - the most you could try is to add fakeroot to the build options.

**Comment by legraina** [comment]
Thank you. I've indeed seen that singularity needs root for the networking options.

**Comment by vsoch** [comment]
hey @legraina I completely agree that it's not well documented when root/sudo is needed, and how you can get around it with fakeroot! I added a section front and center here -> https://singularityhub.github.io/singularity-compose/#/?id=when-do-i-need-sudo

Make sure to clear your cache so you can see it, just pushed! Thanks for bringing this up!
