### ISSUE TITLE
Support environment variables

### ISSUE THREAD

**Issue by pierlauro** [singularityhub/singularity-compose#25]
Hi,
is there any plan to support the definition of environment variables in the singularity-compose file? E.g. as in [docker-compose](https://docs.docker.com/compose/environment-variables/)

**Comment by vsoch** [comment]
Great idea! It totally depends on instance support for external envars... let me do some testing today and I’ll get back to you.

**Comment by pierlauro** [comment]
Docker-compose allows to specify environment variables directly in the configuration file (`environment` section) or to retrieve them from an external file (`env_file` section).

After asking, I actually succeeded to reproduce the `env_file` behavior with a simple workaround: mounting an external file in `/.singularity.d/env/env_file.sh` . It is obviously a temporary solution, but maybe for the definitive one it is just needed to add some syntactic sugar and reuse the already available volume mechanism.

**Comment by vsoch** [comment]
Yes, I've used docker-compose easily 100 times... I'm well aware!

Binding to the container would be a supported solution for the current singularity-compose, however what I'm thinking about are all of the various build options https://sylabs.io/guides/3.5/user-guide/appendix.html that you might want at build and then runtime. I don't know if I'll have time for this today, but it's on my radar, and I won't rush since you have a workaround. Likely we'd need to update singularity python (spython) first, and then the library here.

**Comment by vsoch** [comment]
hey @pierlauro  - I gave this some more thought, and if a custom environment can by added simply by mounting the file, this is a simple solution that I see in favor of adding the section to the recipe file. Please take a look at the environment section I wrote in the docs here:

https://singularityhub.github.io/singularity-compose/#/spec/spec-1.0?id=environment

And if this meets your need and looks okay, I think we are good to close this issue, as the solution is already possible (and not too much of a hack, considering this is how it would be recommended using vanilla Singularity).

**Comment by pierlauro** [comment]
Good to have it documented so it can help other users. I guess we can close as this is a viable solution, thanks!

**Comment by biocyberman** [comment]
Haven't checked where it happens the same with docker-compose, nonetheless it should be mentioned that all environment variables are visible inside the container. So anyone with access to the shell of the container will be able to see them. So sensitive data like plaintext PASSWORDs are visible.

**Comment by vsoch** [comment]
This is sort of standard / expected with Singularity, the environment between host and container is seamless. Would you like to add a note to the docs (for those not familiar with Singularity) to remember that the environment is shared with the host, and if they want complete isolation, to add an argument to clean the environment?

**Comment by vsoch** [comment]
Hmm just thinking - the other option would be to enforce `--clean-env` always, which is more along the lines of docker-compose. What do you think @biocyberman and @pierlauro ?

**Comment by vsoch** [comment]
@biocyberman I'm doing some testing, start will accept --cleanenv but it doesn't really honor it, for example, I have an `RSE_*` set of variables on my host:

```bash
$ singularity instance start --cleanenv docker://busybox web
INFO:    Using cached SIF image
INFO:    instance started successfully
$ singularity shell instance://web
Singularity> env | grep RSE
RSE_CONFIG_FILE=/home/vanessa/Desktop/Code/rseng/software/rse.ini
```
It's on the level of the instance interaction that you need to use `--cleanenv`:

```
$ singularity shell --cleanenv instance://web
# no results
env | grep RSE
```
So I think if you are looking to deploy an application and let someone access, if they have access to the host then they would already have access to those envars in the first place. If they don't, then you would need to control access with adding `--cleanenv`. If you think this is a bug (and the `--cleanenv` for start should work) then it would make sense to open an issue on the Singularity board. Let me know your thoughts - happy to update / change when we have a plan!

**Comment by vsoch** [comment]
@biocyberman this might be a silly question, but if someone has access to shell into the container, and the envars are from the host, wouldn't they already see those envars / secrets? It would be up to the user running `shell` to also add `--cleanenv`.

**Comment by pierlauro** [comment]
> Hmm just thinking - the other option would be to enforce `--clean-env` always, which is more along the lines of docker-compose. What do you think @biocyberman and @pierlauro ?

I think a `--clean-env` flag would be more than appreciated to differenciate host and container variables! The tricky part is deciding whether or not setting it as default; maybe no, since docker users are the ones expecting a clean environment while singularity has explicitly the opposite behaviour

**Comment by vsoch** [comment]
@pierlauro I thought so too, but it seems that start doesn’t honor it (or perhaps the start script does so the service container is clean, that is, until someone shells or execs and brings their environment?

**Comment by biocyberman** [comment]
@vsoch Wow, thanks for the energy :) Let me give you the context: 

I am writing singularity compose with `mariadb` and some other tools for COVID1 (anyone?). It's half working: build successfully, setup database manually, compose `up` and `down` successfully, and and login to the database. The work is based on [sylabs example](https://github.com/sylabs/examples/tree/master/database/mariadb).

In the process I checked docker-compose part in  [mariadb dockerhub page ](https://hub.docker.com/_/mariadb) and wanted to compose the same for mariadb with this end goal: 

1. build, 
2. setup db (with custom database name and username), 
3. secure the server, 
4. start/stop compose to serve mariadb as a service together with other apps/services. 

With that said having PASSWORD hanging around in the container is worrying to me. Users may have unexpected way to query this information, especially something like MYSQL_ROOT_PASSWORD. So it would be better to keep this minimalistic/least exposure by default. I didn't know about `--clean-env`. Will take a look at that. 

On going work is on [biocyberman/singularity-mariadb](https://github.com/biocyberman/singularity-mariadb) repo. Direct help on the repo is welcome :)

**Comment by vsoch** [comment]
@biocyberman if you need the password to start the database, I'm not sure how you expect it to not be present in the container. I think moreso what you need is some client to it (separate from the database that starts) that doesn't have the environment variables added, but allows for some (no auth needed) interaction? If you can better explain how you would intend to start a container and use a password to init the database, but then have the password not in the container, it would be helpful. Can you not just unset it after you start the database? E.g.,
```
%startscript

# run commands to start database
UNSET TOPSECRET_PASSWORD
```
As far as I can tell from the docs you linked, the docker-compose would require / show that envar too.
