### ISSUE TITLE
sudo used when ports are set, causes failure. Cannot set instance start options to set fakeroot network

### ISSUE THREAD

**Issue by briveramelo** [singularityhub/singularity-compose#38]
# Context:
I run a web service that uses 4 docker containers with Gitlab CI/CD, and I'm porting this setup to an HPC environment with singulairty. I am collaborating with my HPC server admin to enable inter-container communication with singularity without using root permissions and instead using fakeroot. Pending their response, we'll be modifying the .../singularity/network/40_fakeroot.conflist file to look like the bridge network config instead of the ptp config, which will hopefully enable this inter-container communication without the need for running with sudo/root.

# Intent
My ported setup uses a shell script to call singularity start + exec/run on each instance, but I'd like to move to singularity compose for a cleaner workflow.

# Issues
However, there are two clear barriers and one unclear maybe/maybe not barrier for this to work in this setup currently.

# Clear Barriers
1. If a port is defined for an instance's compose yaml, singularity-compose uses sudo to start the singularity instance.
[https://github.com/singularityhub/singularity-compose/blob/f8897e107ab7cbba3c6656486a132aeb0699ad35/scompose/project/project.py#L146-L155](https://github.com/singularityhub/singularity-compose/blob/f8897e107ab7cbba3c6656486a132aeb0699ad35/scompose/project/project.py#L146-L155)

2. Instance start options cannot be set. Although we can set build options, start options are missing from the current spec, so I cannot start with the fakeroot network.

# Sludge balls (not quite barriers)
3. Instance run and exec commands cannot be set. When porting from a Docker image, Singularity ignores the "WORKDIR" option, which requires that I use a use a different command to launch the instance. Also, in this new environment, environment variables with non-ascii characters are rejected, so I launch the instance with singularity exec and the `env` command to pass all non-ascii environment variables to the entrypoint script. For both of these quirky scenarios, I cannot rely on the container's default run scripts, and I certainly do not want to maintain separate containers for my CI/CD and production environments

# Ideas
1. Allow setting arbitrary start options per container just like with build options. That could look like a new field `start` with a sub field `start.options`. Part of this change could include a modification to the check for setting `self.sudo` in the linked  section above
2. Add an entrypoint field to the spec. this could look just like the `post.commands` field like `entrypoint.commands`, but now would override any default run script and execute the specified commands within the instance on startup.

**Comment by vsoch** [comment]
We could probably tackle some of these. Can you:

- provide a dummy example for one of your containers you want to bring up
- Show me the command line example to set up networking that works without needing sudo
- What do you mean environment variables are rejected? Can you show me?


I think the easiest thing to do would be for us to work on this together, if you can put what you have so far in a repo and then show me directly what doesn’t work, we can then work through each of these issues (and I can do most of the development as long as I have your guidance on the issue).

**Comment by briveramelo** [comment]
That's great to hear, I'm excited to help. I can do these things, but before we do I want to confirm this inter-container communication is really quite as viable as I think. I'll know when I hear back from the admin, so should be within the next couple days

**Comment by briveramelo** [comment]
Good news: the admin agreed to try the change and it worked. My singularity containers can now communicate on the fakeroot network. 

One of my containers uses environment variables with periods `my.var=val`, so if this line exists in a .env file I pass with the `--env-file` option to run or exec, I get the following error
```
FATAL:   While processing file.env: while evaluating environment script: could not execute "my.var=val": execution is disabled
```
So my current workaround is to put all these odd variables in a space-delineated file and run the exec command like this, though I'm sure there are other, likely simpler workarounds
```
singularity exec --env-file .env instance://app env `cat non-ascii.env` printenv
```
where printenv will just provide visual confirmation that it worked, but normally I call the entrypoint script instead. I did also notice for my other scenario that I can specify the `--pwd <dir>` option to set my initial working directory

I will find a good dummy example with two containers that's a relatively simple plug-and-play. In the meantime, take a look at this setup, as I found these all necessary for this to come together

### Things I found necessary for Inter-Container Communication:
1. Fakeroot Permission as a User
In order to use the fakeroot option, you'll need singularity version 3.3 or above. I'm using 3.7.1. An admin needs to update singularity's fakeroot pid/gid/uid mapping with the /etc/subgid and /etc/subuid files, using the command
`sudo singularity config fakeroot --add <user>`
[https://sylabs.io/guides/3.7/user-guide/cli/singularity_config_fakeroot.html](url)

2. Updated fakeroot network configuration
It's worth saving the original file as backup, but here is what the fakeroot conf looks like now.

`cat /<path>/<to>/singularity/network/40_fakeroot.conflist`
```
{
    "cniVersion": "0.4.0",
    "name": "fakeroot",
    "plugins": [
        {
            "type": "bridge",
            "bridge": "sbr0",
            "isGateway": true,
            "ipMasq": true,
            "ipam": {
                "type": "host-local",
                "subnet": "10.22.0.0/16",
                "routes": [
                    { "dst": "0.0.0.0/0" }
                ]
            }
        },
        {
            "type": "firewall"
        },
        {
            "type": "portmap",
            "capabilities": {"portMappings": true},
            "snat": true
        }
    ]
}
```
Note: The singularity admin guide does have a warning against modifying this file because of the security implications. Someone with better understanding of these implications will want to weigh in. This setup is still tentative for us, pending a more thorough analysis
[https://sylabs.io/guides/3.7/admin-guide/user_namespace.html?highlight=40_fakeroot](url)

3. Instance Options
`-f` or `--fakeroot` and `--net --network-args "portmap=####:####/proto"` options are necessary, where the host ports must be above 1024

For now, I use the following command
`./run.sh >& stdout.txt &`
where the contents of run.sh are:
```
#!/bin/bash

singularity instance start \
-e -C -f -w \
--net --network-args "portmap=8883:8883/tcp" \
/path/to/app.sif app

singularity run instance://app
``` 
and the build options look like this:
`singularity build --fix-perms -f -F -s app.sif "docker://www.path.to/image:tag"`

The `-e` or `--cleanenv` and `-C` or `--containall` are not necessary, but they are part of my setup

**Comment by vsoch** [comment]
Thank you @briveramelo ! I'll be able to take a look this weekend, since it's an outside work project.

**Comment by briveramelo** [comment]
@vsoch wonderful, thank you.

As for a dummy example, I found this to be a lean test

```
singularity pull alpine.sif library://alpine:latest
singularity instance start -f --net alpine.sif alp1
singularity instance start -f --net alpine.sif alp2
singularity exec instance://alp2 ping -c 2 `singularity instance list | grep alp1 | grep -o '10.* '`
```

A successful output from the last command will look like this
```
PING 10.22.0.23 (10.22.0.23): 56 data bytes
64 bytes from 10.22.0.23: seq=0 ttl=64 time=0.099 ms
64 bytes from 10.22.0.23: seq=1 ttl=64 time=0.086 ms

--- 10.22.0.23 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.086/0.092/0.099 ms
```
while a failure might look like
```
PING 10.22.0.23 (10.22.0.23): 56 data bytes

--- 10.22.0.23 ping statistics ---
2 packets transmitted, 0 packets received, 100% packet loss
```

**Comment by vsoch** [comment]
@briveramelo you mentioned wanted to add an entry to the config for network options (or start options) - can you give me an example of what you had in mind? The example provided above only has `--net` - are you saying that given that the user defines custom network args, we forgo the default and use them instead? And then where does fakeroot come in for this step to start the instances? It might help if you can show me what you would want the `singularity-compose.yml` file to look like, and the command that is expected to be generated. Thank you!

**Comment by briveramelo** [comment]
Thank you again for revisiting this. I think this will be an awesome feature.

The `-f` option is equivalent to `--fakeroot`, so for the dummy example above, fakeroot comes in on the same line that starts the instances
```
singularity instance start -f --net alpine.sif alp1
```

Yes, I think it's a fair assumption that any specifically defined network options would be used instead of the defaults.

I didn't consider the dummy setup for capturing all of the requirements I had mentioned originally; I had just considered it a test for inter-container communication. 

The clarification about compose -> command is great. 

singularity-compose.yml
```
version: "1.0"
instances:
  db:
    image: db.sif
    ports:
      - "1025:1025"
    start:
      options: "-f --net --network-args='IP=10.22.0.10'"
    exec:
      options: "--env-file=db.env"
      commands: "custom-entrypoint.sh arg1 arg2"
  api:
    image: api.sif
    ports:
      - "1026:1026"
    start:
      options: "-f --net --network-args='IP=10.22.0.11'"
    depends_on:
      - db
```

`singularity-compose up` would trigger...
```
singularity instance start -f --net --network-args="portmap=1025:1025/tcp" --network-args="IP=10.22.0.10" db.sif db
singularity exec --env-file db.env instance://db custom-entrypoint.sh arg1 arg2
singularity instance start -f --net --network-args="portmap=1026:1026/tcp" --network-args="IP=10.22.0.11" api.sif api
singularity run instance://api
```

**Comment by vsoch** [comment]
hey @briveramelo ! Okay I have something for you to test. To start, I have a PR that will reorganize the singularity-compose-examples folder to include examples for the spec v1.0, and now v2.0 (what we've worked on here). You can find that ping example here: https://github.com/singularityhub/singularity-compose-examples/pull/4/files#diff-70a0c5dcf3d1984dde44c1e48e3ceee2338fe47624fd784565ece7375adcd21f.

Specifically, as we talked about above, there is now support for a start group and an exec group, each of which can have options and a command (exec) or arguments (start). You can see the updated docs for the spec 2.0 here: https://github.com/singularityhub/singularity-compose/pull/41/files#diff-4d8ba6bedc5f5549c157312d69b4bb0938ace20f65810aa7779fb0df812aa10d (which is basically describing the ping example).

I removed the check for sudo to generate a hosts and resolv.conf file, because I think it will be useful regardless - we care most about the instances being able to interact with one another. But let's discuss this - should there be some condition for determining if we want to generate this? Maybe if there is just one instance the host would want to preserve binding the /etc/hosts from the host? Or if we have a case of a user not using fakeroot that wants to have the normal hosts file mapped (and then the containers can't see one another by hostname) that might be another case. We could:

1. have some variable to control that
2. default to doing the mapping if there is >1 instances together
3. or something else?

I hope this is what you had in mind! When you get a chance, please take a look / test / let me know questions / concerns / anything else that you have!

https://github.com/singularityhub/singularity-compose/pull/41

**Comment by briveramelo** [comment]
This is awesome, I'm excited to try it out!

I might not get to it today, but I'll test as soon as I get a chance.

I think your assessment about hostname mapping makes sense. It seems like a reasonable default to include any container using ports or an explicit `--net` option along with sudo or fakeroot. I also don't see a need for adding the mapping with just a single container, so that makes sense too.

I can see maybe one exception to these defaults though
> None is the only network option that can be used by non-privileged users. It isolates the container network from the host network with a loopback interface.

[https://sylabs.io/guides/3.7/user-guide/networking.html](url)

From this, I understand that networking w/ the host network is only enabled for a container when its start, run, exec command includes the `--net` option _and_ does not use the `--net --network none` option. I would think any container started with the `none` network that would not get added to the hosts/resolve.conf files. 

Regarding the IP names, I also don't think should be necessary, I was just adding it as an example of other cli options that might be added. With the use of these host resolution file edits, this should be especially necessary.

I realized I overlooked something with the .yml yesterday. My apologies for the oversight. If I want to add options to `exec`, this is now possible, but not for `run`. If I want to add an `--env-file` or `--containall` to the run options, or anything else for that matter, I can't do this yet. To avoid collision b/w run/exec (as only one should be used to launch the container entrypoint), maybe the yaml should look more like this:

```
version: "1.0"
instances:
  db:
    image: db.sif
    ports:
      - "1025:1025"
    start:
      options: "-f"
    entrypoint:
      options: "--env-file=db.env"
      commands: "custom-entrypoint.sh arg1 arg2"
      # triggers singularity exec --env-file=db.env instance://db custom-entrypoint.sh arg1 arg2
  api:
    image: api.sif
    ports:
      - "1026:1026"
    start:
      options: "-f"
    entrypoint:
      options: "--env-file=api.env"
      # triggers singularity run --env-file=api.env instance://api
    depends_on:
      - db
```
so `entrypoint` with commands would trigger exec and `entrypoint` with only options would trigger run instead.

What do you think?

**Comment by vsoch** [comment]
These are good suggestions! Here are what I think we should do to address them:

I thought about it, and I think it's fairly reasonable to either provide `--net` or  `--net --network none` without sudo or fakeroot. The other use case, not wanting a `--net` at all, I don't think a user would need to use singularity-compose - it's fairly easy to execute a singularity command for that. Singularity compose is for orchestration of containers, meaning the focus really is on getting the networking and services working. But if a user comes along and presents a strong use case for not having either, we can update this in a later version.

For binding the hosts file, I realize that it does include localhost, so it wouldn't hurt to add. If a user presents with a strong use case for not wanting that, we can add a configuration value to disable doing it (again, not adding a feature until it's proven to be needed).

I see the difference between your entrypoint example and having exec, but what about if the user wants to exec a single command, and then a second run command? You are saying it would be okay to enforce one or the other, but not both (I think this is reasonable, but I wonder if there are use cases where it wouldn't work?) Or what if they want to run, but they don't have any options (so it would be an empty section? Is there any reason to not just define another run section alongside exec so the user can explicitly choose?

```yaml
    # Just run the container after startscript
    run: []
```
```yaml
    # Run with options
    run:
        - options: "env-file=myvars.env"
```

**Comment by vsoch** [comment]
okay, I added support for run to the PR! And no worries about taking some time to review - I'll only be able to work on the weekends so it would be another week anyhoo.

**Comment by briveramelo** [comment]
This is great! I think everything you've said and added here makes sense.

I'll definitely take a closer look soon

**Comment by briveramelo** [comment]
I did a git clone, checked out this new branch, uninstalled singularity-compose, reinstalled this new local copy, got some things working, but I ran into a few issues.

Start options appear to work fine, Exec appears to work fine, but using run doesn't seem to work

In the yaml, `run: []`,  `run: options: - anyArgs`, `run: options: - anyArgs command: []`, and `run: options: - anyArgs command: - anyArgs` each fails. It looks like there's an empty string arg being parsed and used, which causes this failure

Note that the entrypoint.sh script referenced below in the error takes all the args passed to it and calls `exec "$@"` on them. The $@ value looks like it gets resolved to '', which is reflected in the final line of this.

```
singularity-compose --debug up 
Creating db
DEBUG singularity instance start <bindings> -e -C -f -w --net --network-args "portmap=1025:1025/tcp" --network-args "IP=10.22.0.2" --hostname db --writable-tmpfs db.sif db 
DEBUG singularity run --env-file=.env instance://db 
/usr/local/bin/entrypoint.sh: line 359: exec: : not found

Traceback (most recent call last):
  File "/.../pip/bin/singularity-compose", line 11, in <module>
    load_entry_point('singularity-compose', 'console_scripts', 'singularity-compose')()
  File "/.../scompose/client/__init__.py", line 255, in start
    main(args=args, parser=parser, extra=extra)
  File "/.../scompose/client/up.py", line 30, in main
    no_resolv=args.no_resolv,
  File "/.../scompose/project/project.py", line 398, in up
    names, command="up", writable_tmpfs=writable_tmpfs, no_resolv=no_resolv
  File "/.../scompose/project/project.py", line 459, in _create
    ip_address=lookup[instance.name],
  File "/.../scompose/project/instance.py", line 508, in up
    self.create(writable_tmpfs=writable_tmpfs, ip_address=ip_address)
  File "/.../scompose/project/instance.py", line 593, in create
    options=self.run_opts,
  File "/.../pip/lib/python3.6/site-packages/spython/utils/terminal.py", line 142, in stream_command
    raise subprocess.CalledProcessError(return_code, cmd)
subprocess.CalledProcessError: Command '['singularity', 'run', '--env-file=.env', 'instance://db', '']' returned non-zero exit status 127.
```

Still playing around to see if there are other issues I can spot

**Comment by briveramelo** [comment]
With this yaml, things work pretty well.

scomp.yml
```
version: "2.0"

instances:

  alp1:
    image: alpine/alpine.sif
    start:
      options:
        - e
        - C
        - f
        - w
    exec:
      command: "echo test"
      # - echo
      # - test
    ports:
      - "3306:3306"

  alp2:
    image: alpine/alpine.sif
    ports:
      - "8883:8883"
    start:
      options:
        - e
        - C
        - f
        - w
    exec:
      options:
        - e
        - C
      command: "ping -c 2 alp1"
```

`singularity-compose --debug -f scomp.yml up` will echo and ping with all options passed as expected

This is more nuanced, and certainly less of a big deal, but triggering these containers in sequence will fail with an IP address collision

```
singularity-compose --debug -f scomp.yml up alp1
singularity-compose --debug -f scomp.yml up alp2
...
FATAL:   container creation failed: failed to allocate for range 0: requested IP address 10.22.0.2 is not available in range set 10.22.0.1-10.22.255.254
```

**Comment by vsoch** [comment]
If you want to insert an IPython, and IPython.embed and can trace what the issue is with the args that would be very helpful!

**Comment by briveramelo** [comment]
Can you clarify? I'm relatively new to the python ecosystem.

The same issue can be replicated with this call and yaml

`singularity-compose --debug -f scomp.yml up`
```
version: "2.0"

instances:

  alp1:
    image: alpine/alpine.sif
    start:
      options:
        - e
        - C
        - f
        - w
    run:
      options:
        - e
    ports:
      - "1025:1025"

  alp2:
    image: alpine/alpine.sif
    ports:
      - "1026:1026"
    start:
      options:
        - e
        - C
        - f
        - w
    exec:
      options:
        - e
        - C
      command: "ping -c 2 alp1"
```

**Comment by vsoch** [comment]
The way I like to debug is to find where in the code that the issue is being raised (in the example of run it would likely be in https://github.com/singularityhub/singularity-compose/blob/add/spec-version-2.0/scompose/project/project.py and https://github.com/singularityhub/singularity-compose/blob/add/spec-version-2.0/scompose/project/instance.py. Write the following anywhere that you want to debug:

```python
print("I'm in section XX")
import IPython
IPython.embed()
```
Then you can run the same command, and interactively look at variables, try commands, until you pin down the issue. It's like an interactive debugger, basically. If you don't have ipython:

```bash
pip install ipython
```
I mention in case you have bandwidth to look, I don't have any time this weekend!

**Comment by vsoch** [comment]
And you can clone and install in development mode (meaning form the local folder) like:

```bash
$ pip install -e .
```
That way you can easily edit / change the files as you explore.

**Comment by briveramelo** [comment]
Great, thank you. My weekends are usually pretty packed, but I'll see if I can pinpoint a line of code all the same

**Comment by vsoch** [comment]
Great! And if not I can usually put in some time during a normal weekend. This weekend I just happen to have a few large chunks of work I want to do (and am pretty excited about!)

**Comment by briveramelo** [comment]
re: IP collision
[https://github.com/singularityhub/singularity-compose/blob/65117a2ed8efab5c76ea1d36e70a7cd80b20f899/scompose/project/project.py#L216](url)
This for loop should check if the next IP is already claimed by some previously started container, and if so skip on to the next IP. Not sure how the singularity-compose project api might allow you to query such a thing, but this variation of the bash line from before should return a list of all those in use. 

`singularity instance list | grep -o '10.* '` if the run with fakeroot
`sudo singularity instance list | grep -o '10.* '` if run with root

These will return different lists, and because this addition means supporting both scenarios, makes sense to check both

**Comment by briveramelo** [comment]
Looks like a copy/paste error

[https://github.com/singularityhub/singularity-compose/blob/65117a2ed8efab5c76ea1d36e70a7cd80b20f899/scompose/project/instance.py#L590](url)
Should say
`args=self.run_args` instead of `args=self.exec_args`

And similarly, this comment should say `run` instead of `exec`
[https://github.com/singularityhub/singularity-compose/blob/65117a2ed8efab5c76ea1d36e70a7cd80b20f899/scompose/project/instance.py#L170](url)

**Comment by vsoch** [comment]
hey @briveramelo !

Whoo! So I wound up saying "Wow, those are just a few quick fixes, and I got up early - I can do that!" and then I went down a huge rabbit hole, because turns out I needed to update singularity Python to support instance list with --json, then the CI broke and I had to refactor, then I had to update the code here to be more flexible about instance list arguments, and finally I was able to test an release Singularity Python 0.1.1 (which is a requirement for this updated version of singularity compose. So now about 5 hours later... I updated the PR (yeah, lol, I'm crying inside).

**Comment by briveramelo** [comment]
Haha, oh my gosh! That's true dedication.

I'll honor those 5 hours and give this a good look through 😀

**Comment by briveramelo** [comment]
I know you've already over-invested on this for the weekend, so no pressure on this.

I can see that the IP collisions are fixed, but now there's an issue with the generated etc.hosts ignoring previous container IP/hostname mappings with sequential calls `singularity-compose up <container>`
[https://github.com/singularityhub/singularity-compose/blob/f8897e107ab7cbba3c6656486a132aeb0699ad35/scompose/project/project.py#L247-L249](https://github.com/singularityhub/singularity-compose/blob/f8897e107ab7cbba3c6656486a132aeb0699ad35/scompose/project/project.py#L247-L249)
I think it's a fair default that all existing containers be added to the new output, so you could reuse bits of the recent fix from here to get those mappings
[https://github.com/singularityhub/singularity-compose/blob/87f6288862defd3fd4c76d1faf9cf030caee4d30/scompose/project/project.py#L222-L228](https://github.com/singularityhub/singularity-compose/blob/87f6288862defd3fd4c76d1faf9cf030caee4d30/scompose/project/project.py#L222-L228)


Also, empty run args in the yaml was still causing the same error as before; the parser was using `''` instead of `None`
I've verified the following changes work in my environment.

[https://github.com/singularityhub/singularity-compose/blob/87f6288862defd3fd4c76d1faf9cf030caee4d30/scompose/project/instance.py#L172-L173](https://github.com/singularityhub/singularity-compose/blob/87f6288862defd3fd4c76d1faf9cf030caee4d30/scompose/project/instance.py#L172-L173)
should look like 
```
self.run_args = run_group.get("args")
if self.run_args and "|" in self.run_args:
```

[https://github.com/singularityhub/singularity-compose/blob/87f6288862defd3fd4c76d1faf9cf030caee4d30/scompose/project/instance.py#L581-L586](https://github.com/singularityhub/singularity-compose/blob/87f6288862defd3fd4c76d1faf9cf030caee4d30/scompose/project/instance.py#L581-L586)
should also update to something like this so that `None` doesn't get printed. There may be a more concise way:
```
if self.run_args:
    commands = "%s %s %s" % (
        " ".join(self.run_opts),
        self.uri,
        self.run_args,
    )
else:
    commands = "%s %s" % (
        " ".join(self.run_opts),
        self.uri,
    )
```

Finally, I just learned how to do proper formatting for all these github hyperlinks, so I went back and fixed all those bad links for posterity!

Thanks for your help with all this. It's coming together quite nicely

**Comment by briveramelo** [comment]
Another show-stopper:

Each container's exec/run commands often continue indefinitely, and the current setup gets stuck on any container that does that and prevents subsequent containers from starting
[https://github.com/singularityhub/singularity-compose/blob/87f6288862defd3fd4c76d1faf9cf030caee4d30/scompose/project/project.py#L458-L478](https://github.com/singularityhub/singularity-compose/blob/87f6288862defd3fd4c76d1faf9cf030caee4d30/scompose/project/project.py#L458-L478)

This snippet ought to run each container detached / in the background so none is waiting indefinitely 

I'm also running into some issues with viewing the output logs: they're empty. If I start a single instance, I can view the stdout, but if I pipe the output to a file or view the logs directly at `.singularity/instances/logs/.../alp1.out`, there is nothing present.

I don't have any suggestions for this last issue about logging just yet.

I've also spent a bit more time than anticipated here, so hopefully these suggestions are more than enough for now

**Comment by vsoch** [comment]
> I can see that the IP collisions are fixed, but now there's an issue with the generated etc.hosts ignoring previous container IP/hostname mappings with sequential calls singularity-compose up <container>

Wouldn't this file be re-written so it wouldn't matter? Why would we want the previous mappings?

**Comment by vsoch** [comment]
> I think it's a fair default that all existing containers be added to the new output, so you could reuse bits of the recent fix from here to get those mappings

Containers that are defined in the singularity-compose.yml are the only ones that should be there. If a service /instance is not defined there, it shouldn't arbitrarily be added to the mapping.

**Comment by vsoch** [comment]
> Each container's exec/run commands often continue indefinitely, and the current setup gets stuck on any container that does that and prevents subsequent containers from starting

I'm not sure it would work to launch a subprocess - it would just be killed when execution ends. For now I think this is the responsibility of the user. If they have an exec or run in the singularity-compose.yml, it's up to them to ensure that it doesn't continue forever. If they need to run a command that's outside of that scope, then they need to use the recipe post section to do it.

And could you please post further comments on the pull request so we can have threaded responses? It's very challenging here.

**Comment by briveramelo** [comment]
Totally agree, it was getting tough for me too. I moved all the unaddressed comments to the PR at their relevant files/lines. I'm new to open-source dev workflows like this, so thank you for your patience as I get acquainted and sorry for creating some frustration.

**Comment by vsoch** [comment]
You’re doing a great job! It’s no worries 😊 👏

**Comment by briveramelo** [comment]
This issue is resolved with the recent PR: [https://github.com/singularityhub/singularity-compose/pull/41](https://github.com/singularityhub/singularity-compose/pull/41)

Just opened a new issue for the persistent containers blocking subsequent containers: [https://github.com/singularityhub/singularity-compose/issues/43](https://github.com/singularityhub/singularity-compose/issues/43)
