### ISSUE TITLE
requested IP address is not available

### ISSUE THREAD

**Issue by maawoo** [singularityhub/singularity-compose#42]
Hi there! 
Currently I run into the following error every time I use `singularity-compose up`, even with any of the [singularity-compose-examples](https://github.com/singularityhub/singularity-compose-examples). I probably broke something myself, but can't figure out what exactly. Any advice?

```
Creating httpd
ERROR:   container cleanup failed: no instance found with name httpd
FATAL:   container creation failed: failed to allocate for range 0: requested IP address 10.22.0.2 is not available in range set 10.22.0.1-10.22.255.254

ERROR ['FATAL:   failed to start instance: while running /usr/local/libexec/singularity/bin/starter: exit status 255\n'] : return code 255
```

**Comment by vsoch** [comment]
That range is the singularity default network, so if you don't have other instances running, you likely don't have network control. I would open an issue on https://github.com/hpcng/singularity and ask about reasons for this particular error, and if you can pin down the issue we can try to change in Singularity Compose here. But if you don't have any access to networking it likely won't work. So I would:

 - look at your singularity network configuration files
 - test starting/stopping instances with networking per the singularity docs
 - open an issue on the singularity repository to figure out the underlying issue (and see if there is a range on your host that are open)

**Comment by maawoo** [comment]
Hi Vanessa,
thanks for your super quick answer! :) 

I was able to figure out what I did wrong and how to fix the resulting problem after finding these two issues: 
https://github.com/containers/podman/issues/3759 and https://github.com/cloudnativelabs/kube-router/issues/383

What I did wrong:
- I deleted all files related to a test-project without properly using `singularity-compose down` first.

How I fixed it: 
- I deleted everything in the directory `/var/lib/cni/networks/bridge` which included a file named after the IP address that was being blocked as mentioned above.

**Comment by vsoch** [comment]
Haha, I've done that a few times with docker-compose and singularity-compose! delete and then "oops, the containers are still running!" and then you have to re-create them to get a handle on them again. I've never deleted files in the bridge direction before, and that would definitely lead to an issue because the port range wouldn't be defined in some configuration. I'm glad that you figured it out - closing issue!
