### ISSUE TITLE
missing version 2.0 example in the doc

### ISSUE THREAD

**Issue by Trophime** [singularityhub/singularity-compose#57]
Hi @vsoch ,
in the docs the version 2.0 example i s missing.
See the doc after: 'here is a version 2.0 spec that shows adding networking and exec options'.

Best
C

**Comment by vsoch** [comment]
Fixed! It looks like I put the full example here https://singularityhub.github.io/singularity-compose/#/spec/spec-2.0?id=singularity-compose-version-20 so I must have forgotten it on the main page. Thanks for the pointer!
