### ISSUE TITLE
Additional Features (healthcheck)

### ISSUE THREAD

**Issue by dlevitas** [singularityhub/singularity-compose#65]
One of my projects utilizes `docker-compose`; recently though, I've been looking to shift to `singularity-compose` due to moving my workflow to my institution's HPC. My `docker-compose.yml` made frequent use of the `healthcheck` parameter, however, I don't see this option in the current documentation and from [this post](https://github.com/compose-spec/compose-spec/issues/64), it appears that such features aren't yet included. I'm curious whether such features can be included for future release?

**Comment by vsoch** [comment]
@dlevitas it definitely could be added, but perhaps what you want to achieve might be done in the post section? That is intended to run after everything, and you could easily put a health check. (see bottom here https://singularityhub.github.io/singularity-compose/#/spec/spec-2.0?id=fields) and an example https://github.com/singularityhub/singularity-compose-examples/blob/286a355520e01c1f082272ad1c22131187a0b985/v1.0/mongodb-pull/singularity-compose.yml#L6.

**Comment by dlevitas** [comment]
Thanks @vsoch I hadn't noticed the `post` option. 

In general, it seem appropriate for many situations, however my `healthcheck` in docker-compose is set like this:

```
healthcheck:
    test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
    interval: 10s
    timeout: 10s
    retries:
        5
```

Presumably the `test` can be accounted by the post section, but It's not clear to me how it would account for the `interval`, `timeout`, and `retries` parameters.

**Comment by vsoch** [comment]
Here is my suggested set of steps that I'd take:

- Engage with Singularity (I typically go to SingularityCE) about if they have an equivalent operation. If so, we can figure out how to plug into it here.
- If not, then we can discuss options. The simpliest idea is to have a limited scoped health check (e.g., bring stuff up and check some number of times and then exit) or we can provide a helper script (to run alongside maybe) as a separate process that does the check. Really what we need to figure out for that is the most effective way to do that.

I'm thinking worst case you could have a few manual checks (via post) that ensure the initial health, and then maybe if you added that same command to some kind of cron job, that would cover repeated checking. If/when there is a clear path forward, then we can talk about implementation details (last step).
